### ISSUE TITLE
Lost connection between HA and NCH2

### ISSUE THREAD

**Issue by studioblabla** [joleys/niko-home-control-II#114]
I use virtual devices to trigger WIFI-switches with NHC2 hardware button. It went well until last week...

Strange behavior:
The initial connection is okay. (Sometimes I need to re-insert UTP or reboot NHC2 to find NHC2 from HA)
After some time (1-2 hours), I can't control lights anymore, and HA doesn't show updates in status when operated from NHC2 (app or buttons).

Or I get the message to reboot HA telling me the config is updated (latest controller config)
Or I get the message 'not available' ("Deze entiteit is niet meer beschikbaar vanuit de nhc2 integratie. Wanneer de entiteit niet meer in gebruik is, kan deze vanuit de instellingen verwijderd worden.")

Some days ago, Google Home lost connection too, but this is ok again.

Modem rebooted, router rebooted,... And Niko support was very friendly, telling me that they don't give support on the API.

**Comment by user152306** [comment]
A wild guess here, your NHC2 controller is sometimes getting new IP-address from DHCP. Try to lock the address for your controller in your "router". If you can't do that, set a static IP-address on the NHC2 controller (if that is possible).

**Comment by studioblabla** [comment]
It's static bij DHCP...

**Comment by tijsverkoyen** [comment]
@studioblabla how stable is the connection? Could it be that the Niko Home Controller disconnect sometimes?
The message that the config is updated is one that happens when Home Assistant and Niko Home Controller (re)connect.

**Comment by studioblabla** [comment]
I changed the UTP cable and plugged it in directly to the router (rebooted the modem).
I'll try other lanport on the NHC.

It looks like, but I'm not sure, that the configuration changes the first time I open a dashboard with all the lights. Like HA is sending something and NHC reacts with a changed config.   

Keep you posted.

**Comment by tijsverkoyen** [comment]
In the integration there is nothing implemented to handle a reconnect at the moment. 
Except for providing an update entity that you should restart Home Assistant.

In most cases the problem is not the controller itself. But the connection (stability).

`2024-01-25 10:17:22.183 DEBUG (Thread-5 (_thread_main)) [custom_components.nhc2.nhccoco.devices.controller] Controller changed (hobby/control/devices/evt == /control/devices/rsp).`

Is a debug statement that is shown when a message for the controller itself is received. See https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/controller.py#L28. This does not mean per se that the connection is lost. 

The behaviour you describe, that Home Assistant is not reacting anymore on any changes for the Niko entities. Happens when the Niko Home Controller republishes the device list. And that is when the update entity should indicate that you need to restart Home Assistant. The republish of the device list, normally, and to my knowledge only happens when the Niko Home Controller restarts, a new version is uploaded to the controller (and restarts) or when the controller lost its connection and reconnects. But as said: the republish of the device list is not handled in this integration as it can be that new entities should be created.

To be frank: At the moment I don't have the time to look into this specific issue due to work obligations.

**Comment by studioblabla** [comment]
No prob Tijs!

**Comment by dimitridelanghe** [comment]
@studioblabla @tijsverkoyen i found out, every time you are uploading a new config from the NHC software u need to reboot the HA, at least for me it's needed!

**Comment by studioblabla** [comment]
@dimitridelanghe: Rebooting was not the solution for me. I need to remove the NHC2 and reinstall it. Even unplug the NHC from the switch and reconnect it to connect to the NHC2.

I tried this week different hardware (Now HA is running on a RPI3, but tried old CPU generic HA, on the CPU Linux + VirtualBox, a recent Windows + VirtualBox), but all had the same behavior. There is a new config and after some time the device is lost in HA.  For some time it looked like a VirtualBox on my macbook worked more stable, but after 2 days, it had the same behavior. 

Now a changed my router (from ddwrt linksys WRT32000 to a low-cost linksys stock firmware) and it's now running for more than 24 hours without issues. I'll update you all in the next few days.

**Comment by tijsverkoyen** [comment]
@studioblabla any update?

**Comment by studioblabla** [comment]
It was running fine for 3 days on a separate small network with its own router. 
Now placed the router and the NHC2 in 'the big' network, and NHC2 'changed config' after 24 hours. 

So what is causing the config-change of the NHC2... Can it be the switch? There are Unifi AP with controller on the network?
So now thinking about replacing the switch... Maybe a have a spare laying around.

**Comment by tijsverkoyen** [comment]
I also have a full Unify setup and no issues at all.
Are you using a static IP for the Niko Home Controller? Could it be that some other device is trying to use the same IP?

**Comment by studioblabla** [comment]
Static lease for NHC2 outside the dhcp range.
Tomorrow, a new ubi-switch will arrive. 
@tijsverkoyen  Where is your HA running on?
Keep you posted!

**Comment by tijsverkoyen** [comment]
Raspberry PI 4 in a docker container

**Comment by studioblabla** [comment]
The new switch did the job. Everything is working stable. 
This topic can be closed!
