### ISSUE TITLE
Not working after upgrade

### ISSUE THREAD

**Issue by 86hakan** [joleys/niko-home-control-II#15]
Hi!
Have you seen any problem after updating HA to get the connection working again?

I have problem with time-out on mqqtt so my connection stop working after restart.

My system is a fieldtest but what i can see there seems that its homeassistant doing time-out.

**Comment by joleys** [comment]
@86hakan: No, I don't have any issues after updating.  I'm installing almost every HA update shortly after it becomes available and did not see any issue in one of the releases.

**Comment by 86hakan** [comment]
Ok. Maybe it is the new version on nhc.

//
Håkan Gundstedt
0735 - 64 34 58

**Comment by BartProvoost** [comment]
@86hakan did you manage to get it fixed?

I'm using this module since September but yesterday it stopped working, possibly after the power went down, but because we're renovating that happens almost every day and it kept working before. In Google and the Niko software it still works, but in Home Assistant all switches are "unavailable".

Any idea what I can do? Reinstall the module?

**Comment by MirandaPoth** [comment]
> @86hakan did you manage to get it fixed?
> 
> I'm using this module since September but yesterday it stopped working, possibly after the power went down, but because we're renovating that happens almost every day and it kept working before. In Google and the Niko software it still works, but in Home Assistant all switches are "unavailable".
> 
> Any idea what I can do? Reinstall the module?

Whenever my Niko restarts, if HA doesn't restart just after it, I have to restart HA. If I'm changing things in Niko and the system updates I have to restart HA. Have you tried this?

Otherwise, do you have any errors in the log?

**Comment by BartProvoost** [comment]
Yes, I restarted it a few times. I looked at the logs but didn't find anything, but maybe I'm not looking at the right logs?

For some reason (only) 1 switch was found by the Zigbee Home Automation integration before I had the hub (not the others), so that one is still available (should reset it to link it to NHC).

**Comment by MirandaPoth** [comment]
Go to Settings, System, Logs, click 'Load full logs' at the bottom then type 'nhc' in the search box. That will show you all the nhc-related log messages.  Any errors?

**Comment by BartProvoost** [comment]
That's what I did, but I didn't see anything useful. I'll restart the hub as well and try again.

**Comment by BartProvoost** [comment]
In the end I removed the integration and added it again. Not sure, but it's possible the ip-address of the hub changed. 

It would be interesting to be able to edit that somewhere?

**Comment by user152306** [comment]
> Whenever my Niko restarts, if HA doesn't restart just after it, I have to restart HA. If I'm changing things in Niko and the system updates I have to restart HA. Have you tried this?
> 
> Otherwise, do you have any errors in the log?

@MirandaPoth is this expected behaviour? I have recently begun to use this integration (thanks everyone for the work) and I have noticed that everytime I update the config in my Niko, the connectivity is broken from HA and the logs filled with "Failed to invoke callback" and restart of HA fixes it. If this is something that is "by design", I think it should be mentioned in the readme, to avoid unnecessary troubleshooting :)

Since I'm quite the new user of this intregration, is there any other situations where this happens and HA must be restarted?

**Comment by MirandaPoth** [comment]
@user152306 Yes this is what happens. Not 'by design' as such, but certainly 'expected behaviour'. I don't find it a problem usually; if I'm changing things in Niko then I know to restart HA when I'm finished.

The only time it's a 'problem' is when we have a power cut. HA is on a UPS but Niko isn't, so the first I know about it is when none of the Niko stuff works. However it does function as a notification that there's been a power cut, as otherwise I probably wouldn't notice!

**Comment by user152306** [comment]
I have the same setup and problem with HA on UPS. 
Is there any nice way of doing a watchdog via an automation to restart HA after NHC reboot/update? My first thought would be to initiate a HA restart based on a log message that needs to looked for, but it feels like there should be a better way via some kind of integration status?

Or, add a binary senor within the intregration that shows the state of the connection, so that an automation for HA restart can easily be implented if wanted.

**Comment by Homergy** [comment]
I'm having the same issue after a reboot of the Niko Controller.
The solution provided by user 152306 would be good if we could implement this somehow.
I see no way to reload the integration without rebooting.

**Comment by tijsverkoyen** [comment]
Just some notes for myself:
* Don't use `systeminfo.published` as this is published multiple times
* Topics `hobby/system/cmd`, `hobby/system/evt`, `hobby/system/rsp` and `hobby/system/err` are not helpful

At this point the best approach would be to check if devices.list is published again, I think.

**Comment by tijsverkoyen** [comment]
If there is someone willing to test: see https://github.com/joleys/niko-home-control-II/pull/67 for the changes.

**Comment by stevo199** [comment]
Hello,

i have also problems after the update. I have to restart HA everyday , to be able to use NHC in HA.

**Comment by blatruwe** [comment]
the #67 seems to work as expected.

**Comment by tijsverkoyen** [comment]
The update entity is added in [v3.1.0](https://github.com/joleys/niko-home-control-II/releases/tag/v3.1.0)
