### ISSUE TITLE
Logbook warning "Failed to invoke callback"

### ISSUE THREAD

**Issue by dsvdglenn** [joleys/niko-home-control-II#21]
Since 2022.8.2 I have the following issue, I don't know if it's related.

Logger: custom_components.nhc2.nhccoco.coco
Source: custom_components/nhc2/nhccoco/coco.py:109
Integration: Niko Home Control II ([documentation](https://github.com/joleys/niko-home-control-II/blob/master/README.md), [issues](https://github.com/joleys/niko-home-control-II))
First occurred: 12:48:45 (2 occurrences)
Last logged: 12:48:55

Failed to invoke callback: 'c6c45601-8f1e-45dc-8e6d-c5e0e0c92f54'

**Comment by 86hakan** [comment]
I also have this problem

**Comment by MirandaPoth** [comment]
It gives this error if you have a device that the nhc2 component doesn't cater for.

**Comment by 86hakan** [comment]
Do you know if it helps to disable it in homeassistant?

**Comment by MirandaPoth** [comment]
I guess disabling that message would be fine, assuming everything is working OK?

**Comment by tijsverkoyen** [comment]
This will only be shown if your logger level is set to `warning`. 

You change this globally in the config.yaml file.

````yaml
# Logger
logger:
  default: error
````

Or you can change the level for the integration specifically:
````yaml
# Logger
logger:
  default: warning
  logs:
    custom_components.nhc2: error
````

See [Home Assistant → Logger](https://www.home-assistant.io/integrations/logger/) for more information.

As @MirandaPoth said, this happens if there is an event for a device that has no callbacks defined. Probably a change for a device that is not (yet) supported.
