### ISSUE TITLE
Trigger on long-hold or multiple switch presses?

### ISSUE THREAD

**Issue by SeBsZ** [joleys/niko-home-control-II#99]
Hi, thanks for your work on this integration. I'm wondering if it is possible to set up automations to trigger not just when a Niko switch is pressed, but also when the switch is held down longer for example. This way I could trigger dim actions for the hue bulbs etc.

I have configured my Niko switches to switch on/off a virtual flag. I can then use your integration to monitor changes to this virtual flag and trigger actions. This works perfectly, but I would like to know if long-presses are supported somehow?

Thanks again

**Comment by tijsverkoyen** [comment]
This is not possible. Niko does not expose the actual switches, only the actions.

Well, they expose them, but there are no "events" triggered on these devices as far as I know. So we don't see presses/long presses.

**Comment by SeBsZ** [comment]
Too bad, thanks for your reply

**Comment by user152306** [comment]
In addition, please send an email to Niko with a feature request that you want to be able to do actions with long-press, shortpress and maybe even hold-action for the same button. This would be great for us since we then can use that in HA based on different virtual devices in Niko per function. I have sent in a request like this to support but they didn't really act on it, so if more ppl do it it can maybe help. Or if someone has a contact in Niko development, please take this to them. As I see it, it would open up a new world for API-users where we suddenly can add one or two extra functions per button (long+hold) in our house without impacting the original function (short) of the button.

**Comment by user152306** [comment]
@SeBsZ there is one thing I have seen in the Niko docs that gives you a little "extra functionality" on a button, maybe this can help your use case in the meantime; https://guide.niko.eu/display/NHCIPE/Using+one+push+button+for+creating+more+than+2+different+scenes

**Comment by SeBsZ** [comment]
Thanks, this is basically what I'm emulating now in Home Assistant. I can push a button x times to "scroll" through different modes. Usually I use this in my children's bedrooms:

Push 1: light 100%
Push 2: light 30%
Push 3: light off
Push 4: repeat

**Comment by SeBsZ** [comment]
Just wanted to chime in here that Niko just added this functionality to v2.22 and I can already use it in HA!

![Image](https://github.com/user-attachments/assets/5c3b6a40-7e04-47f6-a0f4-6998e32fefaf)

Basically in the programming software you can now set a switch to a double function button. This allows you to connect two actions to it instead of one. You can define the long-press duration (2s in this screenshot). I have both actions linked to a virtual device/flag. Then I just read the flags from Home Assistant. Works perfectly!
